version: 2
updates:
    # Maintain changes for python packages:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - Tiernan8r
    # Maintain updates on the github actions:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - Tiernan8r
